version: '3.8'

services:
  database:
    image: postgres:16.3-alpine3.20
    restart: always
    environment:
      POSTGRES_DB: fitness_tracker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      HOST: database
      DIALECT: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      ACCESS_TOKEN_SECRET: your_jwt_secret
      POSTGRES_DB: fitness_tracker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      HOST: database
      DIALECT: postgres
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - database

volumes:
  pgdata:
